/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./test/unit-test.specs.cjs]{@link ./test/unit-test.specs.cjs}
 * 
 **/
import {expect}  from "chai";
/**
 * To generate tests for ESM:
 * $> npm run build:test
 */


describe("On esm/index.esm", () =>
{
    it("should work", function ()
    {
        const result = true;
        expect(result).to.equal(true);
    });

});